# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: properties.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'properties.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10properties.proto\x12\nrealestate\"&\n\nRangeQuery\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\"\x1f\n\x08Geometry\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x02\"0\n\x15SinglePropertyRequest\x12\x17\n\x0fproperty_id_nma\x18\x01 \x01(\t\"K\n\x15\x46ilterPropertyRequest\x12$\n\x04\x61rea\x18\x01 \x01(\x0b\x32\x16.realestate.RangeQuery\x12\x0c\n\x04page\x18\x02 \x01(\x05\"$\n\x11SingleUnitRequest\x12\x0f\n\x07unit_id\x18\x01 \x01(\x03\"\x18\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xb3\x02\n\x0fPropertyService\x12K\n\x10SearchProperties\x12!.realestate.FilterPropertyRequest\x1a\x14.realestate.Response\x12\x46\n\x0bGetProperty\x12!.realestate.SinglePropertyRequest\x1a\x14.realestate.Response\x12K\n\x10GetPropertyUnits\x12!.realestate.SinglePropertyRequest\x1a\x14.realestate.Response\x12>\n\x07GetUnit\x12\x1d.realestate.SingleUnitRequest\x1a\x14.realestate.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'properties_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANGEQUERY']._serialized_start=32
  _globals['_RANGEQUERY']._serialized_end=70
  _globals['_GEOMETRY']._serialized_start=72
  _globals['_GEOMETRY']._serialized_end=103
  _globals['_SINGLEPROPERTYREQUEST']._serialized_start=105
  _globals['_SINGLEPROPERTYREQUEST']._serialized_end=153
  _globals['_FILTERPROPERTYREQUEST']._serialized_start=155
  _globals['_FILTERPROPERTYREQUEST']._serialized_end=230
  _globals['_SINGLEUNITREQUEST']._serialized_start=232
  _globals['_SINGLEUNITREQUEST']._serialized_end=268
  _globals['_RESPONSE']._serialized_start=270
  _globals['_RESPONSE']._serialized_end=294
  _globals['_PROPERTYSERVICE']._serialized_start=297
  _globals['_PROPERTYSERVICE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
